# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-15 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Swiper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField(verbose_name='滑动者ID')),
                ('sid', models.IntegerField(verbose_name='被滑动者ID')),
                ('stype', models.CharField(max_length=16, verbose_name='滑动的类型')),
                ('stime', models.DateTimeField(verbose_name='滑动时间')),
            ],
        ),
    ]
