# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-16 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swiper',
            name='stype',
            field=models.CharField(choices=[('dislike', '左滑'), ('like', '右滑'), ('superlike', '上滑')], max_length=16, verbose_name='滑动的类型'),
        ),
        migrations.AlterUniqueTogether(
            name='swiper',
            unique_together=set([('uid', 'sid')]),
        ),
    ]
