# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-11 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200311_1843'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('dating_location', models.CharField(max_length=10, verbose_name='目标城市')),
                ('min_distance', models.IntegerField(max_length=64, verbose_name='最小查找范围')),
                ('max_distance', models.IntegerField(max_length=64, verbose_name='最大查找范围')),
                ('min_dating_age', models.IntegerField(default=16, max_length=10, verbose_name='最小交友年龄')),
                ('max_dating_age', models.IntegerField(default=80, max_length=10, verbose_name='最大交友年龄')),
                ('dating_sex', models.CharField(max_length=10, verbose_name='匹配的性别')),
                ('vibration', models.BooleanField(default=True, verbose_name='开启震动')),
                ('only_matched', models.BooleanField(default=False, verbose_name='不让陌生人看我的相册')),
                ('auto_play', models.BooleanField(default=True, verbose_name='自动播放视频')),
            ],
        ),
    ]
