# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-19 20:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20200316_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vid_end',
            field=models.DateTimeField(default='2200-02-02', verbose_name='会员过期时间'),
        ),
        migrations.AddField(
            model_name='user',
            name='vip_id',
            field=models.IntegerField(default=1, verbose_name='用户对应的会员ID'),
        ),
    ]
